image: ruby:2.4.2

stages:
  - build
  - test
  - deploy

variables: 
  DATABASE_URL: 'mongodb://mongo/user_posts'

before_script: 
  - cd reddit 
  - bundle install 

build_job:
  stage: build
  tags: my-runner
  script:
    - echo 'Building'

test_unit_job:
  stage: test
  tags: my-runner
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  tags: my-runner
  script:
    - echo 'Testing 2'

deploy_job:
  stage: deploy
  tags: my-runner
  script:
  - echo 'Deploy'
