- name: Install docker
  hosts: all
  become: yes
  vars:
    deploy_user: appuser

  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python
        - python-pip

    - name: Import Docker CE repository gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

    - name: Add Docker CE repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
        state: present

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Install docker-py python package
      pip:
        name: docker-py
