version: '3.3'
services:
  ui:
    volumes:
      - ui_app:/app
    entrypoint: "puma --debug -w 2"
  post:
    volumes:
      - post_app:/app
  comment:
    volumes:
      - comment_app:/app

volumes:
  ui_app:
  comment_app:
  post_app:
